### ISSUE TITLE
typecast symbol int

### ISSUE THREAD

**Issue by catalin-stancu** [alexandruradovici/alf-alfy-asm-language-public#1]
https://github.com/alexandruradovici/alf-alfy-asm-language-public/blob/master/verify/alfy/3_expression/symbol.alfy.asm

here why don't we make a typecast from symbol to int like we did in the test below? i see that it has a comment ; typecast int symbol, but the typecast isn't made. 

https://github.com/alexandruradovici/alf-alfy-asm-language-public/blob/master/verify/alfy/2_simple/symbol.alfy.asm

**Comment by alexandruradovici** [comment]
Symbol -> int is a transparent typecast, as the value (ASCII) from the symbol fits perfectly into an int.
Int -> symbol is a typecast, as an int value might not fit into a symbol. A symbol is 4 bytes, but only the first byte might have a value different from 0.
